### ISSUE TITLE
class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by dnguyen-gc** [Playtika/feign-reactive#284]
Hi.

@kptfh Thank you for responding to issue #280 

Here is my next issue:

spring boot 2.3.2.RELEASE
spring cloud SR6
reactive-feign 2.0.13
```
@ReactiveFeignClient(name = "engine-server-proxy", path = "/api/engine-server")
@CircuitBreaker(name = "standard")
@Retry(name = "standard")
@TimeLimiter(name = "standard")
public interface IEngineClient {
    @PostMapping(value = "/advisor", consumes = "text/xml", produces = "text/xml")
    Mono<ResponseEntity<String>> sendEngineRequest(String engineInput);
}

@Component
public class EngineClient {

    @Autowired
    private IEngineClient iEngineClient;
...
}
```
And I get this:
```
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at reactivefeign.utils.FeignUtils.returnPublisherType(FeignUtils.java:50)
	at reactivefeign.webclient.client.WebReactiveHttpClient.webClient(WebReactiveHttpClient.java:66)
	at reactivefeign.webclient.WebReactiveFeign$Builder.lambda$updateClientFactory$0(WebReactiveFeign.java:65)
	at reactivefeign.ReactiveFeign$Builder$1.create(ReactiveFeign.java:243)
	at reactivefeign.cloud2.CloudReactiveFeign$Builder$1.create(CloudReactiveFeign.java:180)
	at reactivefeign.methodhandler.ReactiveMethodHandlerFactory.create(ReactiveMethodHandlerFactory.java:36)
	at reactivefeign.ReactiveFeign.targetToHandlersByName(ReactiveFeign.java:123)
	at reactivefeign.ReactiveFeign.newInstance(ReactiveFeign.java:76)
	at reactivefeign.ReactiveFeignBuilder.target(ReactiveFeignBuilder.java:114)
	at reactivefeign.ReactiveFeignBuilder.target(ReactiveFeignBuilder.java:104)
	at reactivefeign.spring.config.ReactiveFeignClientFactoryBean.getTarget(ReactiveFeignClientFactoryBean.java:96)
	at reactivefeign.spring.config.ReactiveFeignClientFactoryBean.getObject(ReactiveFeignClientFactoryBean.java:74)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	... 31 more
```
What am I doing wrong here?  Thank you!

**Comment by kptfh** [comment]
Hi. Check this issue #209
