### ISSUE TITLE
Byte array ClassCastException

### ISSUE THREAD

**Issue by Viacheslav-Petriaiev** [Playtika/feign-reactive#314]
Hi

I have the next kotlin method:

`fun getReport(@PathVariable("id") id: String): Mono<ResponseEntity<ByteArray>>`

And I got the next exception:

```
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at reactivefeign.utils.FeignUtils.returnPublisherType(FeignUtils.java:50) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.webclient.client.WebReactiveHttpClient.webClient(WebReactiveHttpClient.java:66) ~[feign-reactor-webclient-2.0.23.jar:na]
	at reactivefeign.webclient.WebReactiveFeign$Builder.lambda$updateClientFactory$0(WebReactiveFeign.java:65) ~[feign-reactor-webclient-2.0.23.jar:na]
	at reactivefeign.ReactiveFeign$Builder$1.create(ReactiveFeign.java:243) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.cloud2.CloudReactiveFeign$Builder$1.create(CloudReactiveFeign.java:180) ~[feign-reactor-cloud2-2.0.23.jar:na]
	at reactivefeign.methodhandler.ReactiveMethodHandlerFactory.create(ReactiveMethodHandlerFactory.java:36) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.ReactiveFeign.targetToHandlersByName(ReactiveFeign.java:123) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.ReactiveFeign.newInstance(ReactiveFeign.java:76) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.ReactiveFeignBuilder.target(ReactiveFeignBuilder.java:114) ~[feign-reactor-core-2.0.23.jar:na]
	at reactivefeign.ReactiveFeignBuilder.target(ReactiveFeignBuilder.java:104) ~[feign-reactor-core-2.0.23.jar:na]
```

Could you help?

Thank you

**Comment by kptfh** [comment]
Can you reproduce it in Java? Is ByteArray converted to Java byte[] ?

**Comment by kptfh** [comment]
Try to wrap byte[] with Mono<byte[]>
Just added test `shouldPassResponseAsRawResponseEntity` that returns `Mono<ResponseEntity<Mono<byte[]>>>`
