### ISSUE TITLE
block()/blockFirst()/blockLast() are blocking error when calling bodyToMono

### ISSUE THREAD

**Issue by a943915349** [Playtika/feign-reactive#390]
here->https://github.com/kptfh/feign-reactive-sample

in this example
when i try feign-server's interface "/greeting"
i get a error "block()/blockFirst()/blockLast() are blocking error when calling bodyToMono AFTER exchange()"
please take a look ,thank u

**Comment by FlyInWind1** [comment]
I have the same problem, this is some of my log

`java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-epoll-3
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83) ~[reactor-core-3.4.7.jar:3.4.7]
	at reactor.core.publisher.Mono.block(Mono.java:1703) ~[reactor-core-3.4.7.jar:3.4.7]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.choose(BlockingLoadBalancerClient.java:150) ~[spring-cloud-loadbalancer-3.0.3.jar:3.0.3]
	at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:88) ~[spring-cloud-openfeign-core-3.0.3.jar:3.0.3]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-10.12.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:?]`

I fond in BlockingLoadBalancerClient.java:150 it called block()

**Comment by a943915349** [comment]
> 这里-> https://github.com/kptfh/feign-reactive-sample
> 
> 在这个例子中，
> 当我尝试 feign-server 的接口“/greeting”时，
> 我收到一个错误“block()/blockFirst()/blockLast() 在调用 bodyToMono AFTER exchange() 时阻塞错误”
> 请看一看，谢谢

I wonder if anyone would like to return to this question
