### ISSUE TITLE
Support of spring-boot 3

### ISSUE THREAD

**Issue by stefferro** [Playtika/feign-reactive#516]
Hi PlaytikaOSS team,

Is there a possibility to support spring-boot 3.0.0 (currently still on milestone release) on a dedicated branch ?

I am experiencing a NoSuchMethodError with the 3.2.6 release
`java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.web.reactive.function.client.ClientResponse.statusCode()'
	at reactivefeign.webclient.client.WebReactiveHttpResponse.status(WebReactiveHttpResponse.java:42)
	at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:45)
	at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:28)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
`

which has been introduced by [this](https://github.com/spring-projects/spring-framework/commit/28ac0d3883e0c683fb995dffc0af7c8a82f3c3d0) change in spring-webflux 6.0.0-M4

**Comment by stefferro** [comment]
Hi, 
Is there a plan to support spring-boot 3 ? If yes, when it is expected ?
Regards

**Comment by soft4rchitecture** [comment]
Hey there, same issue here. 
Is there any plan to migrate feign-reactive to use sprinboot 3 webflux client? 
Is there any schedule ? 
Thanks a lot

**Comment by crimsonvspurple** [comment]
Also curious about spring boot 3 support.

Thank you for this amazing library.

**Comment by kabdev** [comment]
I have another error for spring boot 3.0.1 and feign-reactor-webclient 3.2.6
```
Description:

Parameter 0 of constructor in com.example.demo.BootStrap required a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' that could not be found.


Action:

Consider defining a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' in your configuration.
```

**Comment by tce-saurabhp** [comment]
> I have another error for spring boot 3.0.1 and feign-reactor-webclient 3.2.6
> 
> ```
> Description:
> 
> Parameter 0 of constructor in com.example.demo.BootStrap required a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' that could not be found.
> 
> 
> Action:
> 
> Consider defining a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' in your configuration.
> ```

You can resolve this issue by adding ```@Import(value = ReactiveFeignAutoConfiguration.class)``` to your main application class.

**Comment by wllianwd** [comment]
Also interested here :)

**Comment by wllianwd** [comment]
Here an attempt to add Spring Boot 3 support :).
https://github.com/PlaytikaOSS/feign-reactive/pull/539

**Comment by kptfh** [comment]
After all issues get fixed and the last release of RF library with support of SB2 we will switch to SB3
Just started fixing issues ))

**Comment by Sovannak22** [comment]
> 

Hi is this issue because the library not support Spring version 3?

**Comment by Sovannak22** [comment]
> I have another error for spring boot 3.0.1 and feign-reactor-webclient 3.2.6
> 
> ```
> Description:
> 
> Parameter 0 of constructor in com.example.demo.BootStrap required a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' that could not be found.
> 
> 
> Action:
> 
> Consider defining a bean of type 'reactivefeign.spring.config.ReactiveFeignNamedContextFactory' in your configuration.
> ```

Hi is this issue because the library not support Spring version 3?

**Comment by MazizEsa** [comment]
Workaround @Sovannak22 .


PS. Workaround seem to not work. Forget about this. My bad

@kptfh need any help with the fix so we can move faster?

**Comment by Sovannak22** [comment]
Thank @MazizEsa workaround solution solved the error I'm having now, but now I'm having this error. Is there any workaround solution for this?

> Hi PlaytikaOSS team,
> 
> Is there a possibility to support spring-boot 3.0.0 (currently still on milestone release) on a dedicated branch ?
> 
> I am experiencing a NoSuchMethodError with the 3.2.6 release `java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.web.reactive.function.client.ClientResponse.statusCode()' at reactivefeign.webclient.client.WebReactiveHttpResponse.status(WebReactiveHttpResponse.java:42) at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:45) at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:28) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) `
> 
> which has been introduced by [this](https://github.com/spring-projects/spring-framework/commit/28ac0d3883e0c683fb995dffc0af7c8a82f3c3d0) change in spring-webflux 6.0.0-M4

**Comment by MazizEsa** [comment]
Try spring-cloud-starter-openfeign 3.1.6 @Sovannak22 ?

**Comment by Sovannak22** [comment]
Hi @MazizEsa you mean something like this?
`implementation("org.springframework.cloud:spring-cloud-starter-openfeign:3.1.6")`
or like this?
`implementation("com.playtika.reactivefeign:feign-reactor-spring-cloud-starter:3.1.6")`

**Comment by MazizEsa** [comment]
spring cloud starter feign.

**Comment by Sovannak22** [comment]
@MazizEsa I used this two combined
```
implementation("org.springframework.cloud:spring-cloud-starter-openfeign:3.1.6")
implementation("com.playtika.reactivefeign:feign-reactor-spring-cloud-starter:3.2.6")
```
now I got error 
```
Caused by: java.lang.IllegalStateException: No bean found of type interface org.springframework.cloud.client.loadbalancer.reactive.ReactiveLoadBalancer$Factory for test-cleint
	at reactivefeign.spring.config.ReactiveFeignNamedContext.get(ReactiveFeignNamedContext.java:30) ~[feign-reactor-spring-configuration-3.2.6.jar:na]
	at reactivefeign.spring.config.ReactiveFeignLoadBalancerConfigurator.configure(ReactiveFeignLoadBalancerConfigurator.java:49) ~[feign-reactor-spring-configuration-3.2.6.jar:na]
	at reactivefeign.spring.config.ReactiveFeignClientFactoryBean.applyConfigurators(ReactiveFeignClientFactoryBean.java:105) ~[feign-reactor-spring-configuration-3.2.6.jar:na]
	at reactivefeign.spring.config.ReactiveFeignClientFactoryBean.getTarget(ReactiveFeignClientFactoryBean.java:86) ~[feign-reactor-spring-configuration-3.2.6.jar:na]
	at reactivefeign.spring.config.ReactiveFeignClientFactoryBean.getObject(ReactiveFeignClientFactoryBean.java:74) ~[feign-reactor-spring-configuration-3.2.6.jar:na]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:148) ~[spring-beans-6.0.4.jar:6.0.4]
	... 45 common frames omitted
```
Is there any additional require configuration need?

**Comment by Sovannak22** [comment]
Error with load balancer now gone after I add service discovery but still having error:
`java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.web.reactive.function.client.ClientResponse.statusCode()'
	at reactivefeign.webclient.client.WebReactiveHttpResponse.status(WebReactiveHttpResponse.java:42) ~[feign-reactor-webclient-core-3.1.6.jar:na]
	at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:46) ~[feign-reactor-core-3.1.6.jar:na]
	at reactivefeign.client.StatusHandlerPostProcessor.apply(StatusHandlerPostProcessor.java:28) ~[feign-reactor-core-3.1.6.jar:na]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~`

**Comment by MazizEsa** [comment]
disable reactiveloadbalancer via config?

**Comment by Sovannak22** [comment]
I'm not disable @MazizEsa just add spring-cloud-starter-consul-discovery and register it to consul the error load balancer disappear. Just now still having ClientResponse.statusCode() after include:
`implementation("org.springframework.cloud:spring-cloud-starter-openfeign:3.1.6")`

**Comment by MazizEsa** [comment]
@Sovannak22  looks like you are right. Nothing can be done except revert spring boot to 2.x.x.

**Comment by kptfh** [comment]
please check 4.0.0

**Comment by MazizEsa** [comment]
Nice.
Looking forward to it.
 Thanks for your hardwork @kptfh and everyone.

**Comment by mnbattaglia** [comment]
hi @kptfh ! when 4.0.0 is going to be released?

**Comment by mnbattaglia** [comment]
Nevermind. It is published. I got confused as I didn't see the tag in github
