### ISSUE TITLE
Not able to send application/x-www-form-urlencoded payload in a POST request

### ISSUE THREAD

**Issue by lewis-munene** [Playtika/feign-reactive#524]
This is my code:

```java
@ReactiveFeignClient(value = "keycloak-client", url = "${application.services.keycloak}",
        configuration = ReactiveFeignConfig.class)
public interface KeycloakClient {
    @PostMapping(value = "/protocol/openid-connect/token", 
               consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
    @Headers({
            "Content-Type: application/x-www-form-urlencoded",
            "Accept: */*"
    })
    Mono<Map<String, Object>> logIn(Map<String, ?> form);
}
```
And my config class:
```java
@Configuration
public class ReactiveFeignConfig {

    private final Integer maxInMemorySize;

    public ReactiveFeignConfig(@Value("${webclient.max-in-memory-size}") Integer maxInMemorySize) {
        this.maxInMemorySize = maxInMemorySize;
    }

    @Bean
    Encoder feignFormEncoder(ObjectFactory<HttpMessageConverters> converters) {
        return new SpringFormEncoder(new SpringEncoder(converters));
    }

    @Bean
    public ReactiveHttpRequestInterceptor authorizationInterceptor() {
        //Request interceptor that can add Authorization header dynamically
        return request -> {
            Class<?> clientClass = request.target().type();

            if (clientClass.isAssignableFrom(KeycloakClient.class)) {
                //We're not appending authorization header for Keycloak
                return Mono.just(request);
            }

            String headerValue;

            if (clientClass.isAssignableFrom(UserClient.class)) {
                headerValue = String.format("Bearer %s", JwtResolver.userJwt);
            } else {
                headerValue = "";
            }

            request.headers().put(HttpHeaders.AUTHORIZATION, List.of(headerValue));
            return Mono.just(request);
        };
    }

    @Bean
    @Primary
    public WebClientFeignCustomizer webClientCustomizer() {
        return webClientBuilder -> webClientBuilder.codecs(configurer -> configurer
                .defaultCodecs()
                .maxInMemorySize(maxInMemorySize));
    }
}
```

And I am calling the client as follows:
```java
@Component
@RequiredArgsConstructor
public class UserAccount {
     private final KeycloakClient keycloakClient;

    public void logIn() {
      Map<String, Object> loginDetails = new HashMap<>();

     loginDetails.put("client_id", "xxx");
     loginDetails.put("username", "xxx");
     loginDetails.put("grant_type", "password");
     loginDetails.put("password", "xxx");

      Map<String, Object> map = keycloakClient.logIn(loginDetails)
                    .onErrorMap(e -> new Exception(e.getMessage()))
                    .block()
    }
}
```

When I run this code I get an exception as follows:
```
The connection observed an error

org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'application/x-www-form-urlencoded' not supported for bodyType=java.util.Map<java.lang.String, ?>
	at org.springframework.web.reactive.function.BodyInserters.unsupportedError(BodyInserters.java:391) ~[spring-webflux-5.3.23.jar:5.3.23]
	at org.springframework.web.reactive.function.BodyInserters.lambda$writeWithMessageWriters$11(BodyInserters.java:381) ~[spring-webflux-5.3.23.jar:5.3.23]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
	at org.springframework.web.reactive.function.BodyInserters.writeWithMessageWriters(BodyInserters.java:381) ~[spring-webflux-5.3.23.jar:5.3.23]
	at org.springframework.web.reactive.function.BodyInserters.lambda$fromPublisher$5(BodyInserters.java:205) ~[spring-webflux-5.3.23.jar:5.3.23]
	at org.springframework.web.reactive.function.client.DefaultClientRequestBuilder$BodyInserterRequest.writeTo(DefaultClientRequestBuilder.java:275) ~[spring-webflux-5.3.23.jar:5.3.23]
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$exchange$1(ExchangeFunctions.java:103) ~[spring-webflux-5.3.23.jar:5.3.23]
	at org.springframework.http.client.reactive.ReactorClientHttpConnector.lambda$connect$2(ReactorClientHttpConnector.java:111) ~[spring-web-5.3.23.jar:5.3.23]
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:600) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:440) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:441) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:187) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:444) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:62) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:211) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:847) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:400) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:376) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:368) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1838) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:951) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1409) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

I have tried adding `@RequestBody` annotation to the client declaration like this:
`Mono<Map<String, Object>> logIn(Map<String, ?> form);` but it gives the same results.

Please assist

**Comment by kptfh** [comment]
please check 3.2.10

**Comment by vladimir-narkevich-idf** [comment]
this code worked for me in old version

 ```interface AbsTokenConnector {
  @PostMapping(
    path = ["/protocol/openid-connect/token"],
    consumes = [MediaType.APPLICATION_FORM_URLENCODED_VALUE]
  )
  fun getToken(
    @RequestHeader tracingMetadata: HttpHeaders,
    @RequestBody params: MultiValueMap<String, String>
  ): Mono<TokenResponse>
}
