### ISSUE TITLE
Add support of setting dynamic URI through method parameters

### ISSUE THREAD

**Issue by mkrasilnikow** [Playtika/feign-reactive#627]
In Feign client I can change URI in runtime, without creating new instance of Feign client through builder, like:
```java
    @FeignClient(name = "dummy-name", url = "this-is-a-placeholder")
    public interface MyClient {
        @PostMapping(path = "/create")
        UserDto createUser(URI baseUrl, @RequestBody UserDto userDto);
    }
   //call service:
    URI determinedBasePathUri = URI.create("https://my-host.com");
    myClient.createUser(determinedBasePathUri, userDto);
```

But in ReactiveFeign I can't do so. Only through WebReactiveFeign .builder like this:
```java
IcecreamServiceApi client = 
         WebReactiveFeign  //WebClient based reactive feign  
        .<IcecreamServiceApi>builder()
        .target(IcecreamServiceApi.class, "http://www.myUrl.com")
```

Is it possible to reuse the approach from Feign to ReactiveFeign client?

Thanks!

**Comment by mkrasilnikow** [comment]
Original question from StackOverflow: https://stackoverflow.com/questions/65257778/using-dynamic-url-for-spring-reactivefeignclient

**Comment by marcussatelis** [comment]
WorkAround:

`import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestHeader
import reactivefeign.client.ReactiveHttpRequest
import reactivefeign.client.ReactiveHttpRequestInterceptor
import reactivefeign.spring.config.ReactiveFeignClient
import reactor.core.publisher.Mono

@ReactiveFeignClient(name = "ReactiveDynamicUrlApi", url = BASE_URL, path = "v1/api/product", configuration = ReactiveDynamicUrlApi.RequestInterceptor.class)
interface ReactiveDynamicUrlApi {

    String BASE_URL = "base-url";

    @PostMapping(headers = "Content-Type=application/json")
    Mono<String> post(@RequestHeader(BASE_URL) String baseUrl, @RequestHeader String token, @RequestBody Map requestBody);


    class RequestInterceptor implements ReactiveHttpRequestInterceptor {

        @Override
        public Mono<ReactiveHttpRequest> apply(final ReactiveHttpRequest request) {
            var uri = URI.create(request.headers().get(BASE_URL).getFirst() + request.uri().getPath());
            request.headers().remove(BASE_URL);
            return Mono.just(new ReactiveHttpRequest(request, uri));
        }

    }

}
`

**Comment by marcusvoltolim** [comment]
Workaround with **Java21** using `ReactiveHttpRequestInterceptor` and `@RequestHeader`:

```java
@ReactiveFeignClient(name = "ReactiveDynamicUrlApi", url = BASE_URL, path = "v1/api/product", configuration = ReactiveDynamicUrlApi.RequestInterceptor.class)
interface ReactiveDynamicUrlApi {

    String BASE_URL = "base-url";

    @PostMapping(path = "{id}", headers = "Content-Type=application/json")
    Mono<String> post(@RequestHeader(BASE_URL) String baseUrl, @PathVariable String id, @RequestHeader String token, @RequestBody Map requestBody);


    class RequestInterceptor implements ReactiveHttpRequestInterceptor {

        @Override
        public Mono<ReactiveHttpRequest> apply(final ReactiveHttpRequest request) {
            var uri = URI.create(request.headers().get(BASE_URL).getFirst() + request.uri().getPath());
            request.headers().remove(BASE_URL);
            return Mono.just(new ReactiveHttpRequest(request, uri));
        }

    }

}
```

**Comment by mkrasilnikow** [comment]
found workaround

**Comment by closset703** [comment]
Heads-up for anyone copying the interceptor workaround above — it breaks as soon as the call is retried.

The interceptor removes the header from the request it is handed, but `retryWhen` re-delivers the *same* `ReactiveHttpRequest` instance on re-subscription. So the second attempt finds no header and dies instead of retrying:

```
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)"
  because the return value of "java.util.Map.get(Object)" is null
    at ...RequestInterceptor.apply(RequestInterceptor.java:30)
    at reactivefeign.client.ReactiveHttpExchangeFilterFunction.lambda$ofRequestProcessor$3
    ...
    at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:220)
```

Worth noting `ReactiveHttpRequest` documents itself as immutable — *"All parameters must be effectively immutable, via safe copies, not mutating or otherwise"* — and its copy constructor passes the same headers map through, so removing from the copy has the same effect as removing from the original.

Making the interceptor pure fixes the retry, but then the internal header would be sent on the wire. Stripping it at the WebClient layer instead keeps both properties:

```java
// interceptor: compute the URI, do not touch the request
var uri = URI.create(request.headers().get(BASE_URL).get(0) + request.uri().getPath());
return Mono.just(new ReactiveHttpRequest(request, uri));

// WebClientFeignCustomizer: drop the header just before it goes out
builder.filter((request, next) -> next.exchange(
    request.headers().containsKey(BASE_URL)
        ? ClientRequest.from(request).headers(headers -> headers.remove(BASE_URL)).build()
        : request));
```

Filed #766 for the underlying gap — the `URI` parameter approach from the original post is parsed into `MethodMetadata.urlIndex()` but only honored for `EmptyTarget`, while blocking OpenFeign honors it for a `HardCodedTarget` too.
